// Code generated by the lightning generator from fields.go; DO NOT EDIT.

package enrich

import (
	json "encoding/json"
	"github.com/JohanLindvall/lightning/pkg/unstable"
	"time"
)

// UnmarshalJSON parses JSON into the enrichFields. Fields whose json tag carries the
// "nocopy" option alias the input data instead of copying it; if any are
// present, the caller must keep data unchanged while the result is in use.
func (v *enrichFields) UnmarshalJSON(data []byte) error {
	i := unstable.SkipWS(data, 0)
	if i >= len(data) {
		return unstable.ErrTruncated
	}
	if data[i] == 'n' {
		end, err := unstable.ExpectNull(data, i)
		if err != nil {
			return err
		}
		if unstable.SkipWS(data, end) != len(data) {
			return unstable.ErrInvalidJSON
		}
		return nil
	}
	end, err := lightningGithubComJohanLindvallEnrichenrichFieldsdecodeenrichFields(v, data, i)
	if err != nil {
		return err
	}
	if unstable.SkipWS(data, end) != len(data) {
		return unstable.ErrInvalidJSON
	}
	return nil
}

// UnmarshalJSON parses JSON into the httpResponse. Fields whose json tag carries the
// "nocopy" option alias the input data instead of copying it; if any are
// present, the caller must keep data unchanged while the result is in use.
func (v *httpResponse) UnmarshalJSON(data []byte) error {
	i := unstable.SkipWS(data, 0)
	if i >= len(data) {
		return unstable.ErrTruncated
	}
	if data[i] == 'n' {
		end, err := unstable.ExpectNull(data, i)
		if err != nil {
			return err
		}
		if unstable.SkipWS(data, end) != len(data) {
			return unstable.ErrInvalidJSON
		}
		return nil
	}
	end, err := lightningGithubComJohanLindvallEnrichhttpResponsedecodehttpResponse(v, data, i)
	if err != nil {
		return err
	}
	if unstable.SkipWS(data, end) != len(data) {
		return unstable.ErrInvalidJSON
	}
	return nil
}

func decodeTimeNoCopyLaxValue(v *time.Time, data []byte, i int) (int, error) {
	t, end, err := unstable.ReadTimeLaxOrNull(data, i)
	if err != nil {
		return end, err
	}
	(*v) = t
	i = end
	return i, nil
}

func decodeStringNoCopyLaxValue(v *string, data []byte, i int) (int, error) {
	s, end, err := unstable.ReadStringNoCopyOrNull(data, i)
	if err != nil {
		return end, err
	}
	(*v) = s
	i = end
	return i, nil
}

func lightningGithubComJohanLindvallEnrichenrichFieldsdecodemongoDate(v *mongoDate, data []byte, i int) (int, error) {
	if i >= len(data) {
		return i, unstable.ErrTruncated
	}
	if data[i] == 'n' {
		return unstable.ExpectNull(data, i)
	}
	if data[i] != '{' {
		return i, unstable.ErrExpectObject
	}
	i++
	for first := true; ; first = false {
		if i < len(data) && data[i] <= ' ' {
			i++
			if i < len(data) && data[i] <= ' ' {
				i = unstable.SkipWSRun(data, i+1)
			}
		}
		if i >= len(data) {
			return i, unstable.ErrTruncated
		}
		if data[i] == '}' {
			if first {
				return i + 1, nil
			}
			return i, unstable.ErrInvalidJSON
		}
		var key string
		var ni int
		if i >= len(data) || data[i] != '"' {
			return i, unstable.ErrInvalidJSON
		}
		ks := i + 1
		if k := unstable.IndexCloseOrEscape(data[ks:]); ks+k < len(data) && data[ks+k] == '"' {
			key, ni = unstable.UnsafeStr(data[ks:ks+k]), ks+k+1
		} else {
			var err error
			if key, ni, err = unstable.ReadKey(data, i); err != nil {
				return ni, err
			}
		}
		i = ni
		if i < len(data) && data[i] <= ' ' {
			i++
			if i < len(data) && data[i] <= ' ' {
				i = unstable.SkipWSRun(data, i+1)
			}
		}
		if i >= len(data) || data[i] != ':' {
			return i, unstable.ErrExpectColon
		}
		i = i + 1
		if i < len(data) && data[i] <= ' ' {
			i++
			if i < len(data) && data[i] <= ' ' {
				i = unstable.SkipWSRun(data, i+1)
			}
		}
		if i >= len(data) {
			return i, unstable.ErrTruncated
		}
		switch key {
		case "$date":
			var lax time.Time
			end, err := decodeTimeNoCopyLaxValue(&lax, data, i)
			if err != nil {
				end, err = unstable.SkipValue(data, i)
				if err != nil {
					return end, err
				}
			} else {
				v.Date = lax
			}
			i = end

		default:
			end, err := unstable.SkipValue(data, i)
			if err != nil {
				return end, err
			}
			i = end
		}
		if i < len(data) && data[i] <= ' ' {
			i++
			if i < len(data) && data[i] <= ' ' {
				i = unstable.SkipWSRun(data, i+1)
			}
		}
		if i >= len(data) {
			return i, unstable.ErrTruncated
		}
		if data[i] == '}' {
			return i + 1, nil
		}
		if data[i] != ',' {
			return i, unstable.ErrInvalidJSON
		}
		i++
	}
}

func decodeNumberNoCopyLaxValue(v *json.Number, data []byte, i int) (int, error) {
	s, end, err := unstable.ReadNumberNoCopyOrNull(data, i)
	if err != nil {
		return end, err
	}
	(*v) = json.Number(s)
	i = end
	return i, nil
}

func lightningGithubComJohanLindvallEnrichenrichFieldsdecodeenrichProperties(v *enrichProperties, data []byte, i int) (int, error) {
	if i >= len(data) {
		return i, unstable.ErrTruncated
	}
	if data[i] == 'n' {
		return unstable.ExpectNull(data, i)
	}
	if data[i] != '{' {
		return i, unstable.ErrExpectObject
	}
	i++
	for first := true; ; first = false {
		if i < len(data) && data[i] <= ' ' {
			i++
			if i < len(data) && data[i] <= ' ' {
				i = unstable.SkipWSRun(data, i+1)
			}
		}
		if i >= len(data) {
			return i, unstable.ErrTruncated
		}
		if data[i] == '}' {
			if first {
				return i + 1, nil
			}
			return i, unstable.ErrInvalidJSON
		}
		var key string
		var ni int
		if i >= len(data) || data[i] != '"' {
			return i, unstable.ErrInvalidJSON
		}
		ks := i + 1
		if k := unstable.IndexCloseOrEscape(data[ks:]); ks+k < len(data) && data[ks+k] == '"' {
			key, ni = unstable.UnsafeStr(data[ks:ks+k]), ks+k+1
		} else {
			var err error
			if key, ni, err = unstable.ReadKey(data, i); err != nil {
				return ni, err
			}
		}
		i = ni
		if i < len(data) && data[i] <= ' ' {
			i++
			if i < len(data) && data[i] <= ' ' {
				i = unstable.SkipWSRun(data, i+1)
			}
		}
		if i >= len(data) || data[i] != ':' {
			return i, unstable.ErrExpectColon
		}
		i = i + 1
		if i < len(data) && data[i] <= ' ' {
			i++
			if i < len(data) && data[i] <= ' ' {
				i = unstable.SkipWSRun(data, i+1)
			}
		}
		if i >= len(data) {
			return i, unstable.ErrTruncated
		}
		switch key {
		case "log":
			var lax string
			end, err := decodeStringNoCopyLaxValue(&lax, data, i)
			if err != nil {
				end, err = unstable.SkipValue(data, i)
				if err != nil {
					return end, err
				}
			} else {
				v.Log = lax
			}
			i = end
		case "response":
			var lax string
			end, err := decodeStringNoCopyLaxValue(&lax, data, i)
			if err != nil {
				end, err = unstable.SkipValue(data, i)
				if err != nil {
					return end, err
				}
			} else {
				v.Response = lax
			}
			i = end
		case "httpStatusCode":
			var lax json.Number
			end, err := decodeNumberNoCopyLaxValue(&lax, data, i)
			if err != nil {
				end, err = unstable.SkipValue(data, i)
				if err != nil {
					return end, err
				}
			} else {
				v.HTTPStatusCode = lax
			}
			i = end

		default:
			end, err := unstable.SkipValue(data, i)
			if err != nil {
				return end, err
			}
			i = end
		}
		if i < len(data) && data[i] <= ' ' {
			i++
			if i < len(data) && data[i] <= ' ' {
				i = unstable.SkipWSRun(data, i+1)
			}
		}
		if i >= len(data) {
			return i, unstable.ErrTruncated
		}
		if data[i] == '}' {
			return i + 1, nil
		}
		if data[i] != ',' {
			return i, unstable.ErrInvalidJSON
		}
		i++
	}
}

func lightningGithubComJohanLindvallEnrichenrichFieldsdecodeenrichResponseStatus(v *enrichResponseStatus, data []byte, i int) (int, error) {
	if i >= len(data) {
		return i, unstable.ErrTruncated
	}
	if data[i] == 'n' {
		return unstable.ExpectNull(data, i)
	}
	if data[i] != '{' {
		return i, unstable.ErrExpectObject
	}
	i++
	for first := true; ; first = false {
		if i < len(data) && data[i] <= ' ' {
			i++
			if i < len(data) && data[i] <= ' ' {
				i = unstable.SkipWSRun(data, i+1)
			}
		}
		if i >= len(data) {
			return i, unstable.ErrTruncated
		}
		if data[i] == '}' {
			if first {
				return i + 1, nil
			}
			return i, unstable.ErrInvalidJSON
		}
		var key string
		var ni int
		if i >= len(data) || data[i] != '"' {
			return i, unstable.ErrInvalidJSON
		}
		ks := i + 1
		if k := unstable.IndexCloseOrEscape(data[ks:]); ks+k < len(data) && data[ks+k] == '"' {
			key, ni = unstable.UnsafeStr(data[ks:ks+k]), ks+k+1
		} else {
			var err error
			if key, ni, err = unstable.ReadKey(data, i); err != nil {
				return ni, err
			}
		}
		i = ni
		if i < len(data) && data[i] <= ' ' {
			i++
			if i < len(data) && data[i] <= ' ' {
				i = unstable.SkipWSRun(data, i+1)
			}
		}
		if i >= len(data) || data[i] != ':' {
			return i, unstable.ErrExpectColon
		}
		i = i + 1
		if i < len(data) && data[i] <= ' ' {
			i++
			if i < len(data) && data[i] <= ' ' {
				i = unstable.SkipWSRun(data, i+1)
			}
		}
		if i >= len(data) {
			return i, unstable.ErrTruncated
		}
		switch key {
		case "code":
			var lax json.Number
			end, err := decodeNumberNoCopyLaxValue(&lax, data, i)
			if err != nil {
				end, err = unstable.SkipValue(data, i)
				if err != nil {
					return end, err
				}
			} else {
				v.Code = lax
			}
			i = end

		default:
			end, err := unstable.SkipValue(data, i)
			if err != nil {
				return end, err
			}
			i = end
		}
		if i < len(data) && data[i] <= ' ' {
			i++
			if i < len(data) && data[i] <= ' ' {
				i = unstable.SkipWSRun(data, i+1)
			}
		}
		if i >= len(data) {
			return i, unstable.ErrTruncated
		}
		if data[i] == '}' {
			return i + 1, nil
		}
		if data[i] != ',' {
			return i, unstable.ErrInvalidJSON
		}
		i++
	}
}

func lightningGithubComJohanLindvallEnrichenrichFieldsdecodeenrichFields(v *enrichFields, data []byte, i int) (int, error) {
	if i >= len(data) {
		return i, unstable.ErrTruncated
	}
	if data[i] == 'n' {
		return unstable.ExpectNull(data, i)
	}
	if data[i] != '{' {
		return i, unstable.ErrExpectObject
	}
	i++
	for first := true; ; first = false {
		if i < len(data) && data[i] <= ' ' {
			i++
			if i < len(data) && data[i] <= ' ' {
				i = unstable.SkipWSRun(data, i+1)
			}
		}
		if i >= len(data) {
			return i, unstable.ErrTruncated
		}
		if data[i] == '}' {
			if first {
				return i + 1, nil
			}
			return i, unstable.ErrInvalidJSON
		}
		var key string
		var ni int
		if i >= len(data) || data[i] != '"' {
			return i, unstable.ErrInvalidJSON
		}
		ks := i + 1
		if k := unstable.IndexCloseOrEscape(data[ks:]); ks+k < len(data) && data[ks+k] == '"' {
			key, ni = unstable.UnsafeStr(data[ks:ks+k]), ks+k+1
		} else {
			var err error
			if key, ni, err = unstable.ReadKey(data, i); err != nil {
				return ni, err
			}
		}
		i = ni
		if i < len(data) && data[i] <= ' ' {
			i++
			if i < len(data) && data[i] <= ' ' {
				i = unstable.SkipWSRun(data, i+1)
			}
		}
		if i >= len(data) || data[i] != ':' {
			return i, unstable.ErrExpectColon
		}
		i = i + 1
		if i < len(data) && data[i] <= ' ' {
			i++
			if i < len(data) && data[i] <= ' ' {
				i = unstable.SkipWSRun(data, i+1)
			}
		}
		if i >= len(data) {
			return i, unstable.ErrTruncated
		}
		switch key {
		case "@t", "@timestamp", "timestamp", "Timestamp", "ts", "time", "Time":
			var lax time.Time
			end, err := decodeTimeNoCopyLaxValue(&lax, data, i)
			if err != nil {
				end, err = unstable.SkipValue(data, i)
				if err != nil {
					return end, err
				}
			} else {
				v.Time = lax
			}
			i = end
		case "severity", "Severity", "@l", "@level", "level":
			var lax string
			end, err := decodeStringNoCopyLaxValue(&lax, data, i)
			if err != nil {
				end, err = unstable.SkipValue(data, i)
				if err != nil {
					return end, err
				}
			} else {
				v.Severity = lax
			}
			i = end
		case "traceid", "traceID", "TraceId", "TraceID", "trace_id", "request_id":
			var lax string
			end, err := decodeStringNoCopyLaxValue(&lax, data, i)
			if err != nil {
				end, err = unstable.SkipValue(data, i)
				if err != nil {
					return end, err
				}
			} else {
				v.TraceID = lax
			}
			i = end
		case "spanid", "spanID", "SpanId", "SpanID", "span_id":
			var lax string
			end, err := decodeStringNoCopyLaxValue(&lax, data, i)
			if err != nil {
				end, err = unstable.SkipValue(data, i)
				if err != nil {
					return end, err
				}
			} else {
				v.SpanID = lax
			}
			i = end
		case "sourcecontext", "sourceContext", "SourceContext":
			var lax string
			end, err := decodeStringNoCopyLaxValue(&lax, data, i)
			if err != nil {
				end, err = unstable.SkipValue(data, i)
				if err != nil {
					return end, err
				}
			} else {
				v.SourceContext = lax
			}
			i = end
		case "@i":
			var lax string
			end, err := decodeStringNoCopyLaxValue(&lax, data, i)
			if err != nil {
				end, err = unstable.SkipValue(data, i)
				if err != nil {
					return end, err
				}
			} else {
				v.TemplateHash = lax
			}
			i = end
		case "@mt":
			var lax string
			end, err := decodeStringNoCopyLaxValue(&lax, data, i)
			if err != nil {
				end, err = unstable.SkipValue(data, i)
				if err != nil {
					return end, err
				}
			} else {
				v.Template = lax
			}
			i = end
		case "resourceID", "resourceId", "ResourceId", "resourceUri", "resourceURI":
			var lax string
			end, err := decodeStringNoCopyLaxValue(&lax, data, i)
			if err != nil {
				end, err = unstable.SkipValue(data, i)
				if err != nil {
					return end, err
				}
			} else {
				v.ResourceID = lax
			}
			i = end
		case "eventCategory", "eventcategory", "EventCategory":
			var lax string
			end, err := decodeStringNoCopyLaxValue(&lax, data, i)
			if err != nil {
				end, err = unstable.SkipValue(data, i)
				if err != nil {
					return end, err
				}
			} else {
				v.EventCategory = lax
			}
			i = end
		case "@sv":
			var lax string
			end, err := decodeStringNoCopyLaxValue(&lax, data, i)
			if err != nil {
				end, err = unstable.SkipValue(data, i)
				if err != nil {
					return end, err
				}
			} else {
				v.Version = lax
			}
			i = end
		case "@sn":
			var lax string
			end, err := decodeStringNoCopyLaxValue(&lax, data, i)
			if err != nil {
				end, err = unstable.SkipValue(data, i)
				if err != nil {
					return end, err
				}
			} else {
				v.Service = lax
			}
			i = end
		case "@sp":
			var lax string
			end, err := decodeStringNoCopyLaxValue(&lax, data, i)
			if err != nil {
				end, err = unstable.SkipValue(data, i)
				if err != nil {
					return end, err
				}
			} else {
				v.Product = lax
			}
			i = end
		case "@x":
			var lax string
			end, err := decodeStringNoCopyLaxValue(&lax, data, i)
			if err != nil {
				end, err = unstable.SkipValue(data, i)
				if err != nil {
					return end, err
				}
			} else {
				v.Exception = lax
			}
			i = end
		case "resultType":
			var lax string
			end, err := decodeStringNoCopyLaxValue(&lax, data, i)
			if err != nil {
				end, err = unstable.SkipValue(data, i)
				if err != nil {
					return end, err
				}
			} else {
				v.ResultType = lax
			}
			i = end
		case "resultDescription":
			var lax string
			end, err := decodeStringNoCopyLaxValue(&lax, data, i)
			if err != nil {
				end, err = unstable.SkipValue(data, i)
				if err != nil {
					return end, err
				}
			} else {
				v.ResultDescription = lax
			}
			i = end
		case "log":
			var lax string
			end, err := decodeStringNoCopyLaxValue(&lax, data, i)
			if err != nil {
				end, err = unstable.SkipValue(data, i)
				if err != nil {
					return end, err
				}
			} else {
				v.Log = lax
			}
			i = end
		case "t":
			var lax mongoDate
			end, err := lightningGithubComJohanLindvallEnrichenrichFieldsdecodemongoDate(&lax, data, i)
			if err != nil {
				end, err = unstable.SkipValue(data, i)
				if err != nil {
					return end, err
				}
			} else {
				v.MongoTime = lax
			}
			i = end
		case "s":
			var lax string
			end, err := decodeStringNoCopyLaxValue(&lax, data, i)
			if err != nil {
				end, err = unstable.SkipValue(data, i)
				if err != nil {
					return end, err
				}
			} else {
				v.MongoSeverity = lax
			}
			i = end
		case "response_code", "responseCode", "statusCode", "StatusCode":
			var lax json.Number
			end, err := decodeNumberNoCopyLaxValue(&lax, data, i)
			if err != nil {
				end, err = unstable.SkipValue(data, i)
				if err != nil {
					return end, err
				}
			} else {
				v.ResponseCode = lax
			}
			i = end
		case "grpc_status_number":
			var lax json.Number
			end, err := decodeNumberNoCopyLaxValue(&lax, data, i)
			if err != nil {
				end, err = unstable.SkipValue(data, i)
				if err != nil {
					return end, err
				}
			} else {
				v.GrpcStatusNumber = lax
			}
			i = end
		case "protocol":
			var lax string
			end, err := decodeStringNoCopyLaxValue(&lax, data, i)
			if err != nil {
				end, err = unstable.SkipValue(data, i)
				if err != nil {
					return end, err
				}
			} else {
				v.Protocol = lax
			}
			i = end
		case "response_flags":
			var lax string
			end, err := decodeStringNoCopyLaxValue(&lax, data, i)
			if err != nil {
				end, err = unstable.SkipValue(data, i)
				if err != nil {
					return end, err
				}
			} else {
				v.ResponseFlags = lax
			}
			i = end
		case "properties", "Properties":
			var lax enrichProperties
			end, err := lightningGithubComJohanLindvallEnrichenrichFieldsdecodeenrichProperties(&lax, data, i)
			if err != nil {
				end, err = unstable.SkipValue(data, i)
				if err != nil {
					return end, err
				}
			} else {
				v.Properties = lax
			}
			i = end
		case "responseStatus", "ResponseStatus":
			var lax enrichResponseStatus
			end, err := lightningGithubComJohanLindvallEnrichenrichFieldsdecodeenrichResponseStatus(&lax, data, i)
			if err != nil {
				end, err = unstable.SkipValue(data, i)
				if err != nil {
					return end, err
				}
			} else {
				v.ResponseStatus = lax
			}
			i = end

		default:
			end, err := unstable.SkipValue(data, i)
			if err != nil {
				return end, err
			}
			i = end
		}
		if i < len(data) && data[i] <= ' ' {
			i++
			if i < len(data) && data[i] <= ' ' {
				i = unstable.SkipWSRun(data, i+1)
			}
		}
		if i >= len(data) {
			return i, unstable.ErrTruncated
		}
		if data[i] == '}' {
			return i + 1, nil
		}
		if data[i] != ',' {
			return i, unstable.ErrInvalidJSON
		}
		i++
	}
}

func lightningGithubComJohanLindvallEnrichhttpResponsedecodehttpResponse(v *httpResponse, data []byte, i int) (int, error) {
	if i >= len(data) {
		return i, unstable.ErrTruncated
	}
	if data[i] == 'n' {
		return unstable.ExpectNull(data, i)
	}
	if data[i] != '{' {
		return i, unstable.ErrExpectObject
	}
	i++
	for first := true; ; first = false {
		if i < len(data) && data[i] <= ' ' {
			i++
			if i < len(data) && data[i] <= ' ' {
				i = unstable.SkipWSRun(data, i+1)
			}
		}
		if i >= len(data) {
			return i, unstable.ErrTruncated
		}
		if data[i] == '}' {
			if first {
				return i + 1, nil
			}
			return i, unstable.ErrInvalidJSON
		}
		var key string
		var ni int
		if i >= len(data) || data[i] != '"' {
			return i, unstable.ErrInvalidJSON
		}
		ks := i + 1
		if k := unstable.IndexCloseOrEscape(data[ks:]); ks+k < len(data) && data[ks+k] == '"' {
			key, ni = unstable.UnsafeStr(data[ks:ks+k]), ks+k+1
		} else {
			var err error
			if key, ni, err = unstable.ReadKey(data, i); err != nil {
				return ni, err
			}
		}
		i = ni
		if i < len(data) && data[i] <= ' ' {
			i++
			if i < len(data) && data[i] <= ' ' {
				i = unstable.SkipWSRun(data, i+1)
			}
		}
		if i >= len(data) || data[i] != ':' {
			return i, unstable.ErrExpectColon
		}
		i = i + 1
		if i < len(data) && data[i] <= ' ' {
			i++
			if i < len(data) && data[i] <= ' ' {
				i = unstable.SkipWSRun(data, i+1)
			}
		}
		if i >= len(data) {
			return i, unstable.ErrTruncated
		}
		switch key {
		case "statusCode":
			var lax json.Number
			end, err := decodeNumberNoCopyLaxValue(&lax, data, i)
			if err != nil {
				end, err = unstable.SkipValue(data, i)
				if err != nil {
					return end, err
				}
			} else {
				v.StatusCode = lax
			}
			i = end

		default:
			end, err := unstable.SkipValue(data, i)
			if err != nil {
				return end, err
			}
			i = end
		}
		if i < len(data) && data[i] <= ' ' {
			i++
			if i < len(data) && data[i] <= ' ' {
				i = unstable.SkipWSRun(data, i+1)
			}
		}
		if i >= len(data) {
			return i, unstable.ErrTruncated
		}
		if data[i] == '}' {
			return i + 1, nil
		}
		if data[i] != ',' {
			return i, unstable.ErrInvalidJSON
		}
		i++
	}
}
