// Code generated by the lightning generator from fields.go; DO NOT EDIT.

package enrich

import (
	json "encoding/json"
	"github.com/JohanLindvall/lightning/pkg/unstable"
	"time"
)

// UnmarshalJSON parses JSON into the enrichFields. Fields whose json tag carries the
// "nocopy" option alias the input data instead of copying it; if any are
// present, the caller must keep data unchanged while the result is in use.
func (v *enrichFields) UnmarshalJSON(data []byte) error {
	i := unstable.SkipWS(data, 0)
	if i >= len(data) {
		return unstable.ErrTruncated
	}
	if data[i] == 'n' {
		end, err := unstable.ExpectNull(data, i)
		if err != nil {
			return err
		}
		if unstable.SkipWS(data, end) != len(data) {
			return unstable.ErrInvalidJSON
		}
		return nil
	}
	end, err := lightningGithubComJohanLindvallEnrichenrichFieldsdecodeenrichFields(v, data, i)
	if err != nil {
		return err
	}
	if unstable.SkipWS(data, end) != len(data) {
		return unstable.ErrInvalidJSON
	}
	return nil
}

// UnmarshalJSON parses JSON into the httpResponse. Fields whose json tag carries the
// "nocopy" option alias the input data instead of copying it; if any are
// present, the caller must keep data unchanged while the result is in use.
func (v *httpResponse) UnmarshalJSON(data []byte) error {
	i := unstable.SkipWS(data, 0)
	if i >= len(data) {
		return unstable.ErrTruncated
	}
	if data[i] == 'n' {
		end, err := unstable.ExpectNull(data, i)
		if err != nil {
			return err
		}
		if unstable.SkipWS(data, end) != len(data) {
			return unstable.ErrInvalidJSON
		}
		return nil
	}
	end, err := lightningGithubComJohanLindvallEnrichhttpResponsedecodehttpResponse(v, data, i)
	if err != nil {
		return err
	}
	if unstable.SkipWS(data, end) != len(data) {
		return unstable.ErrInvalidJSON
	}
	return nil
}

func lightningGithubComJohanLindvallEnrichenrichFieldsdecodeTimeNoCopyLaxValue(v *time.Time, data []byte, i int) (int, error) {
	t, end, err := unstable.ReadTimeLaxOrNull(data, i)
	if err != nil {
		return end, err
	}
	(*v) = t
	i = end
	return i, nil
}

func lightningGithubComJohanLindvallEnrichenrichFieldsdecodeStringNoCopyLaxValue(v *string, data []byte, i int) (int, error) {
	s, end, err := unstable.ReadStringNoCopyOrNull(data, i)
	if err != nil {
		return end, err
	}
	(*v) = s
	i = end
	return i, nil
}

func lightningGithubComJohanLindvallEnrichenrichFieldsdecodeNumberNoCopyLaxValue(v *json.Number, data []byte, i int) (int, error) {
	s, end, err := unstable.ReadNumberNoCopyOrNull(data, i)
	if err != nil {
		return end, err
	}
	(*v) = json.Number(s)
	i = end
	return i, nil
}

func lightningGithubComJohanLindvallEnrichenrichFieldsdecodemongoDate(v *mongoDate, data []byte, i int) (int, error) {
	if i >= len(data) {
		return i, unstable.ErrTruncated
	}
	if data[i] == 'n' {
		return unstable.ExpectNull(data, i)
	}
	if data[i] != '{' {
		return i, unstable.ErrExpectObject
	}
	i++
	for first := true; ; first = false {
		if i < len(data) && data[i] <= ' ' {
			i++
			if i < len(data) && data[i] <= ' ' {
				i = unstable.SkipWSRun(data, i+1)
			}
		}
		if i >= len(data) {
			return i, unstable.ErrTruncated
		}
		if data[i] == '}' {
			if first {
				return i + 1, nil
			}
			return i, unstable.ErrInvalidJSON
		}
		var key string
		var ni int
		if i >= len(data) || data[i] != '"' {
			return i, unstable.ErrInvalidJSON
		}
		ks := i + 1
		if k := unstable.IndexCloseOrEscape(data[ks:]); ks+k < len(data) && data[ks+k] == '"' {
			key, ni = unstable.UnsafeStr(data[ks:ks+k]), ks+k+1
		} else {
			var err error
			if key, ni, err = unstable.ReadKey(data, i); err != nil {
				return ni, err
			}
		}
		i = ni
		if i < len(data) && data[i] <= ' ' {
			i++
			if i < len(data) && data[i] <= ' ' {
				i = unstable.SkipWSRun(data, i+1)
			}
		}
		if i >= len(data) || data[i] != ':' {
			return i, unstable.ErrExpectColon
		}
		i = i + 1
		if i < len(data) && data[i] <= ' ' {
			i++
			if i < len(data) && data[i] <= ' ' {
				i = unstable.SkipWSRun(data, i+1)
			}
		}
		if i >= len(data) {
			return i, unstable.ErrTruncated
		}
		switch key {
		case "$date":
			var lax time.Time
			end, err := lightningGithubComJohanLindvallEnrichenrichFieldsdecodeTimeNoCopyLaxValue(&lax, data, i)
			if err != nil {
				end, err = unstable.SkipValue(data, i)
				if err != nil {
					return end, err
				}
			} else {
				v.Date = lax
			}
			i = end

		default:
			end, err := unstable.SkipValue(data, i)
			if err != nil {
				return end, err
			}
			i = end
		}
		if i < len(data) && data[i] <= ' ' {
			i++
			if i < len(data) && data[i] <= ' ' {
				i = unstable.SkipWSRun(data, i+1)
			}
		}
		if i >= len(data) {
			return i, unstable.ErrTruncated
		}
		if data[i] == '}' {
			return i + 1, nil
		}
		if data[i] != ',' {
			return i, unstable.ErrInvalidJSON
		}
		i++
	}
}

func lightningGithubComJohanLindvallEnrichenrichFieldsdecodeenrichProperties(v *enrichProperties, data []byte, i int) (int, error) {
	if i >= len(data) {
		return i, unstable.ErrTruncated
	}
	if data[i] == 'n' {
		return unstable.ExpectNull(data, i)
	}
	if data[i] != '{' {
		return i, unstable.ErrExpectObject
	}
	i++
	for first := true; ; first = false {
		if i < len(data) && data[i] <= ' ' {
			i++
			if i < len(data) && data[i] <= ' ' {
				i = unstable.SkipWSRun(data, i+1)
			}
		}
		if i >= len(data) {
			return i, unstable.ErrTruncated
		}
		if data[i] == '}' {
			if first {
				return i + 1, nil
			}
			return i, unstable.ErrInvalidJSON
		}
		var key string
		var ni int
		if i >= len(data) || data[i] != '"' {
			return i, unstable.ErrInvalidJSON
		}
		ks := i + 1
		if k := unstable.IndexCloseOrEscape(data[ks:]); ks+k < len(data) && data[ks+k] == '"' {
			key, ni = unstable.UnsafeStr(data[ks:ks+k]), ks+k+1
		} else {
			var err error
			if key, ni, err = unstable.ReadKey(data, i); err != nil {
				return ni, err
			}
		}
		i = ni
		if i < len(data) && data[i] <= ' ' {
			i++
			if i < len(data) && data[i] <= ' ' {
				i = unstable.SkipWSRun(data, i+1)
			}
		}
		if i >= len(data) || data[i] != ':' {
			return i, unstable.ErrExpectColon
		}
		i = i + 1
		if i < len(data) && data[i] <= ' ' {
			i++
			if i < len(data) && data[i] <= ' ' {
				i = unstable.SkipWSRun(data, i+1)
			}
		}
		if i >= len(data) {
			return i, unstable.ErrTruncated
		}
		switch key {
		case "log":
			var lax string
			end, err := lightningGithubComJohanLindvallEnrichenrichFieldsdecodeStringNoCopyLaxValue(&lax, data, i)
			if err != nil {
				end, err = unstable.SkipValue(data, i)
				if err != nil {
					return end, err
				}
			} else {
				v.Log = lax
			}
			i = end
		case "response":
			var lax string
			end, err := lightningGithubComJohanLindvallEnrichenrichFieldsdecodeStringNoCopyLaxValue(&lax, data, i)
			if err != nil {
				end, err = unstable.SkipValue(data, i)
				if err != nil {
					return end, err
				}
			} else {
				v.Response = lax
			}
			i = end
		case "httpStatusCode":
			var lax json.Number
			end, err := lightningGithubComJohanLindvallEnrichenrichFieldsdecodeNumberNoCopyLaxValue(&lax, data, i)
			if err != nil {
				end, err = unstable.SkipValue(data, i)
				if err != nil {
					return end, err
				}
			} else {
				v.HTTPStatusCode = lax
			}
			i = end

		default:
			end, err := unstable.SkipValue(data, i)
			if err != nil {
				return end, err
			}
			i = end
		}
		if i < len(data) && data[i] <= ' ' {
			i++
			if i < len(data) && data[i] <= ' ' {
				i = unstable.SkipWSRun(data, i+1)
			}
		}
		if i >= len(data) {
			return i, unstable.ErrTruncated
		}
		if data[i] == '}' {
			return i + 1, nil
		}
		if data[i] != ',' {
			return i, unstable.ErrInvalidJSON
		}
		i++
	}
}

func lightningGithubComJohanLindvallEnrichenrichFieldsdecodeenrichResponseStatus(v *enrichResponseStatus, data []byte, i int) (int, error) {
	if i >= len(data) {
		return i, unstable.ErrTruncated
	}
	if data[i] == 'n' {
		return unstable.ExpectNull(data, i)
	}
	if data[i] != '{' {
		return i, unstable.ErrExpectObject
	}
	i++
	for first := true; ; first = false {
		if i < len(data) && data[i] <= ' ' {
			i++
			if i < len(data) && data[i] <= ' ' {
				i = unstable.SkipWSRun(data, i+1)
			}
		}
		if i >= len(data) {
			return i, unstable.ErrTruncated
		}
		if data[i] == '}' {
			if first {
				return i + 1, nil
			}
			return i, unstable.ErrInvalidJSON
		}
		var key string
		var ni int
		if i >= len(data) || data[i] != '"' {
			return i, unstable.ErrInvalidJSON
		}
		ks := i + 1
		if k := unstable.IndexCloseOrEscape(data[ks:]); ks+k < len(data) && data[ks+k] == '"' {
			key, ni = unstable.UnsafeStr(data[ks:ks+k]), ks+k+1
		} else {
			var err error
			if key, ni, err = unstable.ReadKey(data, i); err != nil {
				return ni, err
			}
		}
		i = ni
		if i < len(data) && data[i] <= ' ' {
			i++
			if i < len(data) && data[i] <= ' ' {
				i = unstable.SkipWSRun(data, i+1)
			}
		}
		if i >= len(data) || data[i] != ':' {
			return i, unstable.ErrExpectColon
		}
		i = i + 1
		if i < len(data) && data[i] <= ' ' {
			i++
			if i < len(data) && data[i] <= ' ' {
				i = unstable.SkipWSRun(data, i+1)
			}
		}
		if i >= len(data) {
			return i, unstable.ErrTruncated
		}
		switch key {
		case "code":
			var lax json.Number
			end, err := lightningGithubComJohanLindvallEnrichenrichFieldsdecodeNumberNoCopyLaxValue(&lax, data, i)
			if err != nil {
				end, err = unstable.SkipValue(data, i)
				if err != nil {
					return end, err
				}
			} else {
				v.Code = lax
			}
			i = end

		default:
			end, err := unstable.SkipValue(data, i)
			if err != nil {
				return end, err
			}
			i = end
		}
		if i < len(data) && data[i] <= ' ' {
			i++
			if i < len(data) && data[i] <= ' ' {
				i = unstable.SkipWSRun(data, i+1)
			}
		}
		if i >= len(data) {
			return i, unstable.ErrTruncated
		}
		if data[i] == '}' {
			return i + 1, nil
		}
		if data[i] != ',' {
			return i, unstable.ErrInvalidJSON
		}
		i++
	}
}

func lightningGithubComJohanLindvallEnrichenrichFieldsdecodeenrichFields(v *enrichFields, data []byte, i int) (int, error) {
	if i >= len(data) {
		return i, unstable.ErrTruncated
	}
	if data[i] == 'n' {
		return unstable.ExpectNull(data, i)
	}
	if data[i] != '{' {
		return i, unstable.ErrExpectObject
	}
	i++
	for first := true; ; first = false {
		if i < len(data) && data[i] <= ' ' {
			i++
			if i < len(data) && data[i] <= ' ' {
				i = unstable.SkipWSRun(data, i+1)
			}
		}
		if i >= len(data) {
			return i, unstable.ErrTruncated
		}
		if data[i] == '}' {
			if first {
				return i + 1, nil
			}
			return i, unstable.ErrInvalidJSON
		}
		var key string
		var ni int
		if i >= len(data) || data[i] != '"' {
			return i, unstable.ErrInvalidJSON
		}
		ks := i + 1
		if k := unstable.IndexCloseOrEscape(data[ks:]); ks+k < len(data) && data[ks+k] == '"' {
			key, ni = unstable.UnsafeStr(data[ks:ks+k]), ks+k+1
		} else {
			var err error
			if key, ni, err = unstable.ReadKey(data, i); err != nil {
				return ni, err
			}
		}
		i = ni
		if i < len(data) && data[i] <= ' ' {
			i++
			if i < len(data) && data[i] <= ' ' {
				i = unstable.SkipWSRun(data, i+1)
			}
		}
		if i >= len(data) || data[i] != ':' {
			return i, unstable.ErrExpectColon
		}
		i = i + 1
		if i < len(data) && data[i] <= ' ' {
			i++
			if i < len(data) && data[i] <= ' ' {
				i = unstable.SkipWSRun(data, i+1)
			}
		}
		if i >= len(data) {
			return i, unstable.ErrTruncated
		}
		switch len(key) {
		case 1:
			switch key {
			case "t":
				var lax mongoDate
				end, err := lightningGithubComJohanLindvallEnrichenrichFieldsdecodemongoDate(&lax, data, i)
				if err != nil {
					end, err = unstable.SkipValue(data, i)
					if err != nil {
						return end, err
					}
				} else {
					v.MongoTime = lax
				}
				i = end
			case "s":
				var lax string
				end, err := lightningGithubComJohanLindvallEnrichenrichFieldsdecodeStringNoCopyLaxValue(&lax, data, i)
				if err != nil {
					end, err = unstable.SkipValue(data, i)
					if err != nil {
						return end, err
					}
				} else {
					v.MongoSeverity = lax
				}
				i = end
			default:
				goto lightningSkipKey
			}
		case 2:
			switch key {
			case "@t", "ts":
				var lax time.Time
				end, err := lightningGithubComJohanLindvallEnrichenrichFieldsdecodeTimeNoCopyLaxValue(&lax, data, i)
				if err != nil {
					end, err = unstable.SkipValue(data, i)
					if err != nil {
						return end, err
					}
				} else {
					v.Time = lax
				}
				i = end
			case "@l":
				var lax string
				end, err := lightningGithubComJohanLindvallEnrichenrichFieldsdecodeStringNoCopyLaxValue(&lax, data, i)
				if err != nil {
					end, err = unstable.SkipValue(data, i)
					if err != nil {
						return end, err
					}
				} else {
					v.Severity = lax
				}
				i = end
			case "@m":
				var lax string
				end, err := lightningGithubComJohanLindvallEnrichenrichFieldsdecodeStringNoCopyLaxValue(&lax, data, i)
				if err != nil {
					end, err = unstable.SkipValue(data, i)
					if err != nil {
						return end, err
					}
				} else {
					v.Message = lax
				}
				i = end
			case "@i":
				var lax string
				end, err := lightningGithubComJohanLindvallEnrichenrichFieldsdecodeStringNoCopyLaxValue(&lax, data, i)
				if err != nil {
					end, err = unstable.SkipValue(data, i)
					if err != nil {
						return end, err
					}
				} else {
					v.TemplateHash = lax
				}
				i = end
			case "@x":
				var lax string
				end, err := lightningGithubComJohanLindvallEnrichenrichFieldsdecodeStringNoCopyLaxValue(&lax, data, i)
				if err != nil {
					end, err = unstable.SkipValue(data, i)
					if err != nil {
						return end, err
					}
				} else {
					v.Exception = lax
				}
				i = end
			default:
				goto lightningSkipKey
			}
		case 3:
			switch key {
			case "msg":
				var lax string
				end, err := lightningGithubComJohanLindvallEnrichenrichFieldsdecodeStringNoCopyLaxValue(&lax, data, i)
				if err != nil {
					end, err = unstable.SkipValue(data, i)
					if err != nil {
						return end, err
					}
				} else {
					v.Message = lax
				}
				i = end
			case "@mt":
				var lax string
				end, err := lightningGithubComJohanLindvallEnrichenrichFieldsdecodeStringNoCopyLaxValue(&lax, data, i)
				if err != nil {
					end, err = unstable.SkipValue(data, i)
					if err != nil {
						return end, err
					}
				} else {
					v.Template = lax
				}
				i = end
			case "@sv":
				var lax string
				end, err := lightningGithubComJohanLindvallEnrichenrichFieldsdecodeStringNoCopyLaxValue(&lax, data, i)
				if err != nil {
					end, err = unstable.SkipValue(data, i)
					if err != nil {
						return end, err
					}
				} else {
					v.Version = lax
				}
				i = end
			case "@sn":
				var lax string
				end, err := lightningGithubComJohanLindvallEnrichenrichFieldsdecodeStringNoCopyLaxValue(&lax, data, i)
				if err != nil {
					end, err = unstable.SkipValue(data, i)
					if err != nil {
						return end, err
					}
				} else {
					v.Service = lax
				}
				i = end
			case "@sp":
				var lax string
				end, err := lightningGithubComJohanLindvallEnrichenrichFieldsdecodeStringNoCopyLaxValue(&lax, data, i)
				if err != nil {
					end, err = unstable.SkipValue(data, i)
					if err != nil {
						return end, err
					}
				} else {
					v.Product = lax
				}
				i = end
			case "log":
				var lax string
				end, err := lightningGithubComJohanLindvallEnrichenrichFieldsdecodeStringNoCopyLaxValue(&lax, data, i)
				if err != nil {
					end, err = unstable.SkipValue(data, i)
					if err != nil {
						return end, err
					}
				} else {
					v.Log = lax
				}
				i = end
			default:
				goto lightningSkipKey
			}
		case 4:
			switch key {
			case "time", "Time":
				var lax time.Time
				end, err := lightningGithubComJohanLindvallEnrichenrichFieldsdecodeTimeNoCopyLaxValue(&lax, data, i)
				if err != nil {
					end, err = unstable.SkipValue(data, i)
					if err != nil {
						return end, err
					}
				} else {
					v.Time = lax
				}
				i = end
			default:
				goto lightningSkipKey
			}
		case 5:
			switch key {
			case "level":
				var lax string
				end, err := lightningGithubComJohanLindvallEnrichenrichFieldsdecodeStringNoCopyLaxValue(&lax, data, i)
				if err != nil {
					end, err = unstable.SkipValue(data, i)
					if err != nil {
						return end, err
					}
				} else {
					v.Severity = lax
				}
				i = end
			default:
				goto lightningSkipKey
			}
		case 6:
			switch key {
			case "@level":
				var lax string
				end, err := lightningGithubComJohanLindvallEnrichenrichFieldsdecodeStringNoCopyLaxValue(&lax, data, i)
				if err != nil {
					end, err = unstable.SkipValue(data, i)
					if err != nil {
						return end, err
					}
				} else {
					v.Severity = lax
				}
				i = end
			case "spanid", "spanId", "spanID", "SpanId", "SpanID":
				var lax string
				end, err := lightningGithubComJohanLindvallEnrichenrichFieldsdecodeStringNoCopyLaxValue(&lax, data, i)
				if err != nil {
					end, err = unstable.SkipValue(data, i)
					if err != nil {
						return end, err
					}
				} else {
					v.SpanID = lax
				}
				i = end
			case "logger":
				var lax string
				end, err := lightningGithubComJohanLindvallEnrichenrichFieldsdecodeStringNoCopyLaxValue(&lax, data, i)
				if err != nil {
					end, err = unstable.SkipValue(data, i)
					if err != nil {
						return end, err
					}
				} else {
					v.SourceContext = lax
				}
				i = end
			default:
				goto lightningSkipKey
			}
		case 7:
			switch key {
			case "message", "Message", "MESSAGE":
				var lax string
				end, err := lightningGithubComJohanLindvallEnrichenrichFieldsdecodeStringNoCopyLaxValue(&lax, data, i)
				if err != nil {
					end, err = unstable.SkipValue(data, i)
					if err != nil {
						return end, err
					}
				} else {
					v.Message = lax
				}
				i = end
			case "traceid", "traceId", "traceID", "TraceId", "TraceID":
				var lax string
				end, err := lightningGithubComJohanLindvallEnrichenrichFieldsdecodeStringNoCopyLaxValue(&lax, data, i)
				if err != nil {
					end, err = unstable.SkipValue(data, i)
					if err != nil {
						return end, err
					}
				} else {
					v.TraceID = lax
				}
				i = end
			case "span_id", "span.id":
				var lax string
				end, err := lightningGithubComJohanLindvallEnrichenrichFieldsdecodeStringNoCopyLaxValue(&lax, data, i)
				if err != nil {
					end, err = unstable.SkipValue(data, i)
					if err != nil {
						return end, err
					}
				} else {
					v.SpanID = lax
				}
				i = end
			default:
				goto lightningSkipKey
			}
		case 8:
			switch key {
			case "severity", "Severity":
				var lax string
				end, err := lightningGithubComJohanLindvallEnrichenrichFieldsdecodeStringNoCopyLaxValue(&lax, data, i)
				if err != nil {
					end, err = unstable.SkipValue(data, i)
					if err != nil {
						return end, err
					}
				} else {
					v.Severity = lax
				}
				i = end
			case "trace_id", "trace.id":
				var lax string
				end, err := lightningGithubComJohanLindvallEnrichenrichFieldsdecodeStringNoCopyLaxValue(&lax, data, i)
				if err != nil {
					end, err = unstable.SkipValue(data, i)
					if err != nil {
						return end, err
					}
				} else {
					v.TraceID = lax
				}
				i = end
			case "protocol":
				var lax string
				end, err := lightningGithubComJohanLindvallEnrichenrichFieldsdecodeStringNoCopyLaxValue(&lax, data, i)
				if err != nil {
					end, err = unstable.SkipValue(data, i)
					if err != nil {
						return end, err
					}
				} else {
					v.Protocol = lax
				}
				i = end
			default:
				goto lightningSkipKey
			}
		case 9:
			switch key {
			case "timestamp", "Timestamp":
				var lax time.Time
				end, err := lightningGithubComJohanLindvallEnrichenrichFieldsdecodeTimeNoCopyLaxValue(&lax, data, i)
				if err != nil {
					end, err = unstable.SkipValue(data, i)
					if err != nil {
						return end, err
					}
				} else {
					v.Time = lax
				}
				i = end
			case "log.level", "levelname":
				var lax string
				end, err := lightningGithubComJohanLindvallEnrichenrichFieldsdecodeStringNoCopyLaxValue(&lax, data, i)
				if err != nil {
					end, err = unstable.SkipValue(data, i)
					if err != nil {
						return end, err
					}
				} else {
					v.Severity = lax
				}
				i = end
			case "exception":
				var lax string
				end, err := lightningGithubComJohanLindvallEnrichenrichFieldsdecodeStringNoCopyLaxValue(&lax, data, i)
				if err != nil {
					end, err = unstable.SkipValue(data, i)
					if err != nil {
						return end, err
					}
				} else {
					v.Exception = lax
				}
				i = end
			default:
				goto lightningSkipKey
			}
		case 10:
			switch key {
			case "@timestamp":
				var lax time.Time
				end, err := lightningGithubComJohanLindvallEnrichenrichFieldsdecodeTimeNoCopyLaxValue(&lax, data, i)
				if err != nil {
					end, err = unstable.SkipValue(data, i)
					if err != nil {
						return end, err
					}
				} else {
					v.Time = lax
				}
				i = end
			case "request_id":
				var lax string
				end, err := lightningGithubComJohanLindvallEnrichenrichFieldsdecodeStringNoCopyLaxValue(&lax, data, i)
				if err != nil {
					end, err = unstable.SkipValue(data, i)
					if err != nil {
						return end, err
					}
				} else {
					v.TraceID = lax
				}
				i = end
			case "loggerName":
				var lax string
				end, err := lightningGithubComJohanLindvallEnrichenrichFieldsdecodeStringNoCopyLaxValue(&lax, data, i)
				if err != nil {
					end, err = unstable.SkipValue(data, i)
					if err != nil {
						return end, err
					}
				} else {
					v.SourceContext = lax
				}
				i = end
			case "resourceID", "resourceId", "ResourceId":
				var lax string
				end, err := lightningGithubComJohanLindvallEnrichenrichFieldsdecodeStringNoCopyLaxValue(&lax, data, i)
				if err != nil {
					end, err = unstable.SkipValue(data, i)
					if err != nil {
						return end, err
					}
				} else {
					v.ResourceID = lax
				}
				i = end
			case "error.type":
				var lax string
				end, err := lightningGithubComJohanLindvallEnrichenrichFieldsdecodeStringNoCopyLaxValue(&lax, data, i)
				if err != nil {
					end, err = unstable.SkipValue(data, i)
					if err != nil {
						return end, err
					}
				} else {
					v.ErrorType = lax
				}
				i = end
			case "resultType":
				var lax string
				end, err := lightningGithubComJohanLindvallEnrichenrichFieldsdecodeStringNoCopyLaxValue(&lax, data, i)
				if err != nil {
					end, err = unstable.SkipValue(data, i)
					if err != nil {
						return end, err
					}
				} else {
					v.ResultType = lax
				}
				i = end
			case "statusCode", "StatusCode":
				var lax json.Number
				end, err := lightningGithubComJohanLindvallEnrichenrichFieldsdecodeNumberNoCopyLaxValue(&lax, data, i)
				if err != nil {
					end, err = unstable.SkipValue(data, i)
					if err != nil {
						return end, err
					}
				} else {
					v.ResponseCode = lax
				}
				i = end
			case "properties", "Properties":
				var lax enrichProperties
				end, err := lightningGithubComJohanLindvallEnrichenrichFieldsdecodeenrichProperties(&lax, data, i)
				if err != nil {
					end, err = unstable.SkipValue(data, i)
					if err != nil {
						return end, err
					}
				} else {
					v.Properties = lax
				}
				i = end
			default:
				goto lightningSkipKey
			}
		case 11:
			switch key {
			case "traceparent", "Traceparent", "TraceParent":
				var lax string
				end, err := lightningGithubComJohanLindvallEnrichenrichFieldsdecodeStringNoCopyLaxValue(&lax, data, i)
				if err != nil {
					end, err = unstable.SkipValue(data, i)
					if err != nil {
						return end, err
					}
				} else {
					v.Traceparent = lax
				}
				i = end
			case "logger_name":
				var lax string
				end, err := lightningGithubComJohanLindvallEnrichenrichFieldsdecodeStringNoCopyLaxValue(&lax, data, i)
				if err != nil {
					end, err = unstable.SkipValue(data, i)
					if err != nil {
						return end, err
					}
				} else {
					v.SourceContext = lax
				}
				i = end
			case "resourceUri", "resourceURI":
				var lax string
				end, err := lightningGithubComJohanLindvallEnrichenrichFieldsdecodeStringNoCopyLaxValue(&lax, data, i)
				if err != nil {
					end, err = unstable.SkipValue(data, i)
					if err != nil {
						return end, err
					}
				} else {
					v.ResourceID = lax
				}
				i = end
			case "status_code":
				var lax json.Number
				end, err := lightningGithubComJohanLindvallEnrichenrichFieldsdecodeNumberNoCopyLaxValue(&lax, data, i)
				if err != nil {
					end, err = unstable.SkipValue(data, i)
					if err != nil {
						return end, err
					}
				} else {
					v.ResponseCode = lax
				}
				i = end
			default:
				goto lightningSkipKey
			}
		case 12:
			switch key {
			case "severityText", "SeverityText":
				var lax string
				end, err := lightningGithubComJohanLindvallEnrichenrichFieldsdecodeStringNoCopyLaxValue(&lax, data, i)
				if err != nil {
					end, err = unstable.SkipValue(data, i)
					if err != nil {
						return end, err
					}
				} else {
					v.Severity = lax
				}
				i = end
			case "service.name":
				var lax string
				end, err := lightningGithubComJohanLindvallEnrichenrichFieldsdecodeStringNoCopyLaxValue(&lax, data, i)
				if err != nil {
					end, err = unstable.SkipValue(data, i)
					if err != nil {
						return end, err
					}
				} else {
					v.Service = lax
				}
				i = end
			case "responseCode":
				var lax json.Number
				end, err := lightningGithubComJohanLindvallEnrichenrichFieldsdecodeNumberNoCopyLaxValue(&lax, data, i)
				if err != nil {
					end, err = unstable.SkipValue(data, i)
					if err != nil {
						return end, err
					}
				} else {
					v.ResponseCode = lax
				}
				i = end
			default:
				goto lightningSkipKey
			}
		case 13:
			switch key {
			case "sourcecontext", "sourceContext", "SourceContext":
				var lax string
				end, err := lightningGithubComJohanLindvallEnrichenrichFieldsdecodeStringNoCopyLaxValue(&lax, data, i)
				if err != nil {
					end, err = unstable.SkipValue(data, i)
					if err != nil {
						return end, err
					}
				} else {
					v.SourceContext = lax
				}
				i = end
			case "eventCategory", "eventcategory", "EventCategory":
				var lax string
				end, err := lightningGithubComJohanLindvallEnrichenrichFieldsdecodeStringNoCopyLaxValue(&lax, data, i)
				if err != nil {
					end, err = unstable.SkipValue(data, i)
					if err != nil {
						return end, err
					}
				} else {
					v.EventCategory = lax
				}
				i = end
			case "error.message":
				var lax string
				end, err := lightningGithubComJohanLindvallEnrichenrichFieldsdecodeStringNoCopyLaxValue(&lax, data, i)
				if err != nil {
					end, err = unstable.SkipValue(data, i)
					if err != nil {
						return end, err
					}
				} else {
					v.ErrorMessage = lax
				}
				i = end
			case "response_code":
				var lax json.Number
				end, err := lightningGithubComJohanLindvallEnrichenrichFieldsdecodeNumberNoCopyLaxValue(&lax, data, i)
				if err != nil {
					end, err = unstable.SkipValue(data, i)
					if err != nil {
						return end, err
					}
				} else {
					v.ResponseCode = lax
				}
				i = end
			default:
				goto lightningSkipKey
			}
		case 14:
			switch key {
			case "severityNumber":
				var lax json.Number
				end, err := lightningGithubComJohanLindvallEnrichenrichFieldsdecodeNumberNoCopyLaxValue(&lax, data, i)
				if err != nil {
					end, err = unstable.SkipValue(data, i)
					if err != nil {
						return end, err
					}
				} else {
					v.SeverityNumber = lax
				}
				i = end
			case "exception.type":
				var lax string
				end, err := lightningGithubComJohanLindvallEnrichenrichFieldsdecodeStringNoCopyLaxValue(&lax, data, i)
				if err != nil {
					end, err = unstable.SkipValue(data, i)
					if err != nil {
						return end, err
					}
				} else {
					v.ErrorType = lax
				}
				i = end
			case "response_flags":
				var lax string
				end, err := lightningGithubComJohanLindvallEnrichenrichFieldsdecodeStringNoCopyLaxValue(&lax, data, i)
				if err != nil {
					end, err = unstable.SkipValue(data, i)
					if err != nil {
						return end, err
					}
				} else {
					v.ResponseFlags = lax
				}
				i = end
			case "responseStatus", "ResponseStatus":
				var lax enrichResponseStatus
				end, err := lightningGithubComJohanLindvallEnrichenrichFieldsdecodeenrichResponseStatus(&lax, data, i)
				if err != nil {
					end, err = unstable.SkipValue(data, i)
					if err != nil {
						return end, err
					}
				} else {
					v.ResponseStatus = lax
				}
				i = end
			default:
				goto lightningSkipKey
			}
		case 15:
			switch key {
			case "severity_number":
				var lax json.Number
				end, err := lightningGithubComJohanLindvallEnrichenrichFieldsdecodeNumberNoCopyLaxValue(&lax, data, i)
				if err != nil {
					end, err = unstable.SkipValue(data, i)
					if err != nil {
						return end, err
					}
				} else {
					v.SeverityNumber = lax
				}
				i = end
			case "service.version":
				var lax string
				end, err := lightningGithubComJohanLindvallEnrichenrichFieldsdecodeStringNoCopyLaxValue(&lax, data, i)
				if err != nil {
					end, err = unstable.SkipValue(data, i)
					if err != nil {
						return end, err
					}
				} else {
					v.Version = lax
				}
				i = end
			default:
				goto lightningSkipKey
			}
		case 17:
			if key[0:16] == "exception.messag" && key[16:] == "e" {
				var lax string
				end, err := lightningGithubComJohanLindvallEnrichenrichFieldsdecodeStringNoCopyLaxValue(&lax, data, i)
				if err != nil {
					end, err = unstable.SkipValue(data, i)
					if err != nil {
						return end, err
					}
				} else {
					v.ErrorMessage = lax
				}
				i = end
			} else if key[0:16] == "error.stack_trac" && key[16:] == "e" {
				var lax string
				end, err := lightningGithubComJohanLindvallEnrichenrichFieldsdecodeStringNoCopyLaxValue(&lax, data, i)
				if err != nil {
					end, err = unstable.SkipValue(data, i)
					if err != nil {
						return end, err
					}
				} else {
					v.ErrorStack = lax
				}
				i = end
			} else if key[0:16] == "resultDescriptio" && key[16:] == "n" {
				var lax string
				end, err := lightningGithubComJohanLindvallEnrichenrichFieldsdecodeStringNoCopyLaxValue(&lax, data, i)
				if err != nil {
					end, err = unstable.SkipValue(data, i)
					if err != nil {
						return end, err
					}
				} else {
					v.ResultDescription = lax
				}
				i = end
			} else {
				goto lightningSkipKey
			}
		case 18:
			if key[0:16] == "grpc_status_numb" && key[16:] == "er" {
				var lax json.Number
				end, err := lightningGithubComJohanLindvallEnrichenrichFieldsdecodeNumberNoCopyLaxValue(&lax, data, i)
				if err != nil {
					end, err = unstable.SkipValue(data, i)
					if err != nil {
						return end, err
					}
				} else {
					v.GrpcStatusNumber = lax
				}
				i = end
			} else {
				goto lightningSkipKey
			}
		case 20:
			if key[0:16] == "exception.stackt" && key[16:] == "race" {
				var lax string
				end, err := lightningGithubComJohanLindvallEnrichenrichFieldsdecodeStringNoCopyLaxValue(&lax, data, i)
				if err != nil {
					end, err = unstable.SkipValue(data, i)
					if err != nil {
						return end, err
					}
				} else {
					v.ErrorStack = lax
				}
				i = end
			} else {
				goto lightningSkipKey
			}
		case 25:
			if key[0:16] == "http.response.st" && key[16:] == "atus_code" {
				var lax json.Number
				end, err := lightningGithubComJohanLindvallEnrichenrichFieldsdecodeNumberNoCopyLaxValue(&lax, data, i)
				if err != nil {
					end, err = unstable.SkipValue(data, i)
					if err != nil {
						return end, err
					}
				} else {
					v.ResponseCode = lax
				}
				i = end
			} else {
				goto lightningSkipKey
			}
		default:
			goto lightningSkipKey
		}
		goto lightningKeyDone
	lightningSkipKey:
		{
			end, err := unstable.SkipValue(data, i)
			if err != nil {
				return end, err
			}
			i = end
		}
	lightningKeyDone:
		if i < len(data) && data[i] <= ' ' {
			i++
			if i < len(data) && data[i] <= ' ' {
				i = unstable.SkipWSRun(data, i+1)
			}
		}
		if i >= len(data) {
			return i, unstable.ErrTruncated
		}
		if data[i] == '}' {
			return i + 1, nil
		}
		if data[i] != ',' {
			return i, unstable.ErrInvalidJSON
		}
		i++
	}
}

func lightningGithubComJohanLindvallEnrichhttpResponsedecodeNumberNoCopyLaxValue(v *json.Number, data []byte, i int) (int, error) {
	s, end, err := unstable.ReadNumberNoCopyOrNull(data, i)
	if err != nil {
		return end, err
	}
	(*v) = json.Number(s)
	i = end
	return i, nil
}

func lightningGithubComJohanLindvallEnrichhttpResponsedecodehttpResponse(v *httpResponse, data []byte, i int) (int, error) {
	if i >= len(data) {
		return i, unstable.ErrTruncated
	}
	if data[i] == 'n' {
		return unstable.ExpectNull(data, i)
	}
	if data[i] != '{' {
		return i, unstable.ErrExpectObject
	}
	i++
	for first := true; ; first = false {
		if i < len(data) && data[i] <= ' ' {
			i++
			if i < len(data) && data[i] <= ' ' {
				i = unstable.SkipWSRun(data, i+1)
			}
		}
		if i >= len(data) {
			return i, unstable.ErrTruncated
		}
		if data[i] == '}' {
			if first {
				return i + 1, nil
			}
			return i, unstable.ErrInvalidJSON
		}
		var key string
		var ni int
		if i >= len(data) || data[i] != '"' {
			return i, unstable.ErrInvalidJSON
		}
		ks := i + 1
		if k := unstable.IndexCloseOrEscape(data[ks:]); ks+k < len(data) && data[ks+k] == '"' {
			key, ni = unstable.UnsafeStr(data[ks:ks+k]), ks+k+1
		} else {
			var err error
			if key, ni, err = unstable.ReadKey(data, i); err != nil {
				return ni, err
			}
		}
		i = ni
		if i < len(data) && data[i] <= ' ' {
			i++
			if i < len(data) && data[i] <= ' ' {
				i = unstable.SkipWSRun(data, i+1)
			}
		}
		if i >= len(data) || data[i] != ':' {
			return i, unstable.ErrExpectColon
		}
		i = i + 1
		if i < len(data) && data[i] <= ' ' {
			i++
			if i < len(data) && data[i] <= ' ' {
				i = unstable.SkipWSRun(data, i+1)
			}
		}
		if i >= len(data) {
			return i, unstable.ErrTruncated
		}
		switch key {
		case "statusCode":
			var lax json.Number
			end, err := lightningGithubComJohanLindvallEnrichhttpResponsedecodeNumberNoCopyLaxValue(&lax, data, i)
			if err != nil {
				end, err = unstable.SkipValue(data, i)
				if err != nil {
					return end, err
				}
			} else {
				v.StatusCode = lax
			}
			i = end

		default:
			end, err := unstable.SkipValue(data, i)
			if err != nil {
				return end, err
			}
			i = end
		}
		if i < len(data) && data[i] <= ' ' {
			i++
			if i < len(data) && data[i] <= ' ' {
				i = unstable.SkipWSRun(data, i+1)
			}
		}
		if i >= len(data) {
			return i, unstable.ErrTruncated
		}
		if data[i] == '}' {
			return i + 1, nil
		}
		if data[i] != ',' {
			return i, unstable.ErrInvalidJSON
		}
		i++
	}
}
